### ISSUE TITLE
This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

### ISSUE THREAD

**Issue by jwwthu** [Daniel-Wu/AfroMNIST#1]
Hi,
I am unable to clone or pull from Github because of a git-lfs quota.

When I clone,
`Cloning into 'F:\Github\AfroMNIST'...
remote: Enumerating objects: 39, done.        
remote: Counting objects: 100% (39/39), done.        
remote: Compressing objects: 100% (38/38), done.        
remote: Total 39 (delta 4), reused 22 (delta 0), pack-reused 0        
Receiving objects: 100% (39/39), 7.47 KiB | 7.47 MiB/s, done.
Resolving deltas: 100% (4/4), done.
Downloading Ethiopic/Ethiopic_MNIST_X_test.npy (63 MB)
Error downloading object: Ethiopic/Ethiopic_MNIST_X_test.npy (d30f3bf): Smudge error: Error downloading Ethiopic/Ethiopic_MNIST_X_test.npy (d30f3bf6a76f318fe7fea1f33e697afc95484c100a7c48823f82e9a13ec99838): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to F:\Github\AfroMNIST\.git\lfs\logs\20200925T121257.3318721.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Ethiopic/Ethiopic_MNIST_X_test.npy: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'`

**Comment by Daniel-Wu** [comment]
We've added the Zenodo and Kaggle links, which shouldn't be subject to bandwidth issues.
